### ISSUE TITLE
Play configuration is not updating while remote configuration is updated

### ISSUE THREAD

**Issue by jeberdson** [play-rconf/play-rconf-http#1]
I have hosted a http file server which contains my application.conf file.
I have started the application with "application.mode=dev" in the application.conf.

I wrote a rest API in my controller to get the current configuration details. i.e., 

def getActiveProfile: Action[AnyContent] = Action { request =>
    Ok(config.getString("application.mode"))
  }

Using postman I sent a request, a got a response as "dev"

After sometime, I changed the "application.mode=prod" in the application.conf file.
Now I tested using postman, but the response is unchanged. It still remains "dev"

Can you please tell me what I am missing here?

**Comment by thibaultmeyer** [comment]
Hello,

Any log ? warn or error ?

Could you past your configuration file (only play-rconf part) and your ApplicationLoader (if you have override it).

**Comment by jeberdson** [comment]
Hi @thibaultmeyer ,
No error or warning has occurred. The problem I guess is play loads the configuration in 2 ways.,
1.  During play server startup
2. If any changes occurred in any files the sbt reloads the configuration.

For my case, I cannot do both the things because I want my server to act as production mode.

**application.conf** (This configuration file is inside the server itself.)

```
application.mode = dev
play {
  application {
    loader = "io.playrconf.ApplicationLoaderScala"
  }
}

remote-configuration {
  provider = "io.playrconf.provider.HttpProvider"
  http {
    url="http://localhost:8080/application.conf"
  }
}
```

**application.conf** (This is the remote application.conf file is present in an http server)

```
application.name = websocket-server
application.mode = prod
application.log = INFO
akka.http {
  log-config-on-start = true
}
play.http.secret.key = "abcdefghijk"
play.server.http.idleTimeout = infinite
```

I have not override ApplicationLoader

**Comment by thibaultmeyer** [comment]
thanks, which version of Play are you using ? _X.Y.Z (JAVA or SCALA)_

**Comment by jeberdson** [comment]
Play 2.7.2 
Scala 2.12.8

**Comment by thibaultmeyer** [comment]
If I understand the problem correctly. Do you want the application to reload the configuration when you edit your remote file?

This behaviour is not implemented in dev mode and not possible in production. As stated in Play's javadoc: "In prod mode, the ApplicationLoader will be instantiated and called once when the application is started."

**Comment by jeberdson** [comment]
@thibaultmeyer 
> If I understand the problem correctly. Do you want the application to reload the configuration when you edit your remote file?

Yes you are correct.

If I want to achieve the application conf to be updated at runtime, what should I do?
I want to make it act like a spring-cloud-config-server.
Your suggestions are highly appreciated.

**Comment by PierreAdam** [comment]
Hello @jeberdson,

As the Play Framework settings shouldn't be modified at runtime, maybe you could have your own instance of the config that would be updated at regular intervals from an actor.

But if you go for something like that, in my mind it would be really important that you separate the Config from Play than your own Config that might get updated. The reason is that you basically can't "trust" your own Config as it might change any time.

**Comment by jeberdson** [comment]
@PierreAdam , @thibaultmeyer 

> As the Play Framework settings shouldn't be modified at runtime, maybe you could have your own instance of the config that would be updated at regular intervals from an actor.

Let me write what I understood.,
My idea is to have a separate instance of the config running behind a http file server. I will have separate config-repo in github and using jenkins I will push the config file to that file server.
From my application, I will schedule an actor to pick the config from the remote server.

Is my understanding correct? please correct me if I am wrong

**Comment by PierreAdam** [comment]
Hi @jeberdson,

I made a small diagram just to be sure but yeah that's pretty much what I would do if I had to do it this way.

![Untitled Diagram (1)](https://user-images.githubusercontent.com/1321787/65408520-c1c9fc00-dde5-11e9-8f86-87aeab71e850.png)

But that being said, it's seems to be a bit weird to had such configuration system. The reason being that it's only gonna be useful in your own code. It will not be supported by any library or plugins for Play. 
The more I think about it, the more I find that what you need is a configuration table on your database and going through the configuration isn't a good option for what you wanna do.

**Comment by jeberdson** [comment]
Hi @PierreAdam ,
First of all thanks for your great support in helping me out. Appreciate it.
I understand your idea, but still there may be a case where I want to modify the database configuration which you have mentioned in the green box. For example, we use sqlserver as the database, it will ask us to change the password for every 90 days. So in this case I need to pull down the server to modify the database configuration.

**Comment by PierreAdam** [comment]
Hi @jeberdson,

In that case, I wouldn't bother to try to cheat the system. The best thing would be to use this plugin and to simply do a reboot of your application to reload all the configuration. This can be done automatically by the CI if you do a simple script that restart your application. If you're in docker, you can just modify a random environment variable then it's gonna restart everything automatically.

It's in my mind the cleanest way to do it.

**Comment by jeberdson** [comment]
Yes I agree with your point @PierreAdam , I will close this issue.

Thanks for your support. In future if you found any solution please update here.

If I got any solution to solve this problem I will post here.
