### ISSUE TITLE
Throw exception if the remote file is not found

### ISSUE THREAD

**Issue by jeberdson** [play-rconf/play-rconf-http#3]
Hi @thibaultmeyer ,

I am using play-rconf-http for fetching the config file from github in my play application.

```
play {
  application {
    loader = "io.playrconf.ApplicationLoaderScala"
  }
}

remote-configuration {
  provider = "io.playrconf.provider.HttpProvider"
  http {
    url = "https://raw.github.ford.com/demo-project/demo/master/demo-server/demo-server-dev.conf?token=AAAD5JXC6DYJABCDXEFSNS5S3RVS"
  }
}
```

I want HttpProvider to throw an exception if the remote-file(demo-server-dev.conf) does not exist in the github(destination folder).

Can you add that feature? 

Thanks in advance.

**Comment by thibaultmeyer** [comment]
Hello,

Indeed it is something that can be interesting to implement. I should have time to do it this weekend, at the very least, early next week.

**Comment by jeberdson** [comment]
@thibaultmeyer ,

That's fine, take your time. It is just a request.

Thank you for your support.

**Comment by thibaultmeyer** [comment]
Hello @jeberdson,

You can now use the last version of `play-rconf-http` (19.09).

**Comment by jeberdson** [comment]
Hi @thibaultmeyer ,
Thank you for implementing it in a short time.
Appreciate your support.
